pipelines:
  - name: app_python
    configuration:
      environmentVariables:
        readOnly:
#          art_url: http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory
          pythonRepo: asgardian-python
          pythonPromoteRepo: asgardian-python-uat-local
          myDockerImageName: docker-dev-local.artifactory-eu.soleng-emea-staging.jfrog.team/python-build
    steps:
     - name: build_app_python
       type: DockerBuild
       configuration:
         dockerFileLocation: CI/DockerBuild/ 
         dockerFileName: Dockerfile
         dockerImageName: ${mydDockerImageName}
         dockerImageTag: ${run_number}
         dockerOptions: --build-arg BUILD_NAME=python-greeting --build-arg BUILD_NUMBER=${run_number}  --build-arg ARTY_URL=${int_artifactory_url} --build-arg ARTY_USER=${int_artifactory_user}  --build-arg ARTY_APIKEY=${int_artifactory_apikey} --build-arg ARTY_MAIN_REPO=${pythonRepo} 
         inputResources:
           - name: src_code_app_python
         outputResources: 
           - name: bi_app_python
         integrations:
           - name: artifactory_eu
     - name: scan_app_python
       type: XrayScan
       configuration:
#          failOnScan: false
         inputResources:
           - name: bi_app_python
             trigger: true
        #  outputResources: 
        #     - name: scanned_python_BuildInfo
     - name: python_promote
       type: PromoteBuild
       configuration:
         targetRepository:      ${pythonPromoteRepo} 
         includeDependencies:   false   
         status:                Passed
         comment:               Artifact passed Xray Scan
         copy:                  false
         inputSteps:
           - name: scan_app_python    # optional
             trigger: true       
         intputResources:
           - name: bi_app_python 
         outputResources:
           - name: pb_app_python 